package com.quintiles.biibexport.util;

import java.security.MessageDigest;

/**
 * Utility class to generate MD5 hash for the login call. This class is used for generating the
 * Login Response Tokens and used in subsequent checks.
 */
public class GenerateTokenMD5 {

	private String token;

    public GenerateTokenMD5(String value)
    {
	    try{
            value = value + ":" + System.currentTimeMillis();
	    	MessageDigest md = MessageDigest.getInstance("MD5");
	        md.update(value.getBytes());
	        byte byteData[] = md.digest();
	        //convert the byte to hex format method 1
	        StringBuffer sb = new StringBuffer();
	        for (int i = 0; i < byteData.length; i++) {
	         sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
	        }
	        this.token = sb.toString();
    	}catch(Exception ex) {}
	}

    /**
     * Retrieve the Token generated by this class
     *
     * @return string containing the md5 hash
     */
	public String getToken(){
		return this.token;
	}
}